local gen = {}
gen.name = "fstab"

local base_entries = {
  -- /proc, /sys, /dev are mounted by initramfs and OpenRC devfs/sysfs services.
  -- Do NOT add them here — they conflict with OpenRC service ordering.
  { "tmpfs",    "/run",            "tmpfs",     "nosuid,nodev,mode=0755",            "0", "0" },
  { "tmpfs",    "/tmp",            "tmpfs",     "nosuid,nodev,mode=1777",            "0", "0" },
  { "tmpfs",    "/var/log",        "tmpfs",     "nosuid,nodev,mode=0755",            "0", "0" },
  { "tmpfs",    "/var/cache",      "tmpfs",     "nosuid,nodev,mode=0755",            "0", "0" },
  -- /var/lib is NOT tmpfs — iwd, dbus, and other services need persistent state here
  { "tmpfs",    "/var/tmp",        "tmpfs",     "nosuid,nodev,mode=1777",            "0", "0" },
  { "tmpfs",    "/var/lock",       "tmpfs",     "nosuid,nodev,mode=0755",            "0", "0" },
}

local function render_entry(e)
  return e[1] .. "\t" .. e[2] .. "\t" .. e[3] .. "\t" .. e[4] .. "\t" .. e[5] .. "\t" .. e[6]
end

local function detect_root_spec(sync, current)
  -- Prefer existing root line in fstab
  if current then
    for line in (current .. "\n"):gmatch("([^\n]*)\n") do
      if not line:match("^%s*#") and not line:match("^%s*$") then
        -- fields: spec  mountpoint  fstype  ...
        local spec, mnt = line:match("^(%S+)%s+(%S+)")
        if mnt == "/" and spec and not spec:match("^(proc|sysfs|devtmpfs|devpts|tmpfs)$") then
          return spec
        end
      end
    end
  end

  local uuid = sync.shell_output("findmnt -n -o UUID /")
  if uuid and uuid ~= "" then
    return "UUID=" .. uuid
  end
  local partuuid = sync.shell_output("findmnt -n -o PARTUUID /")
  if partuuid and partuuid ~= "" then
    return "PARTUUID=" .. partuuid
  end
  local src = sync.shell_output("findmnt -n -o SOURCE / | sed 's/\\[.*\\]//'")
  if src and src ~= "" then
    return src
  end
  return nil
end

local function detect_boot_line(current)
  if not current then return nil end
  for line in (current .. "\n"):gmatch("([^\n]*)\n") do
    if not line:match("^%s*#") and not line:match("^%s*$") then
      local _, mnt = line:match("^(%S+)%s+(%S+)")
      if mnt == "/boot" then
        return line
      end
    end
  end
  return nil
end


function gen.plan(cfg, sync)
  local path = "/etc/fstab"
  local current = sync.read_file(path) or ""

  local lines = {
    "# /etc/fstab — generated by haliade-synchronize",
    "#",
  }
  for _, e in ipairs(base_entries) do
    table.insert(lines, render_entry(e))
  end

  local root_spec = detect_root_spec(sync, current)
  if root_spec then
    table.insert(lines, "")
    table.insert(lines, "# btrfs generations layout")
    table.insert(lines, render_entry({
      root_spec, "/", "btrfs", "subvol=@,defaults,noatime", "0", "1"
    }))
    table.insert(lines, render_entry({
      root_spec, "/.snapshots", "btrfs", "subvol=@snapshots,defaults,noatime", "0", "0"
    }))
  else
    io.stderr:write("[warn] fstab: could not detect root device; skipping btrfs entries\n")
  end

  local boot_line = detect_boot_line(current)
  if boot_line then
    table.insert(lines, "")
    table.insert(lines, "# boot")
    table.insert(lines, boot_line)
  end

  if cfg.fstab.extra_mounts and #cfg.fstab.extra_mounts > 0 then
    table.insert(lines, "")
    table.insert(lines, "# extra mounts")
    for _, m in ipairs(cfg.fstab.extra_mounts) do
      local spec = m.device
      if m.uuid then spec = "UUID=" .. m.uuid end
      if m.partuuid then spec = "PARTUUID=" .. m.partuuid end
      table.insert(lines, render_entry({
        spec,
        m.mountpoint,
        m.fstype or "ext4",
        m.options or "defaults,nosuid,nodev",
        tostring(m.dump or 0),
        tostring(m.pass or 2),
      }))
    end
  end

  table.insert(lines, "")
  local desired = table.concat(lines, "\n")

  if current == desired then return {} end

  return {
    sync.change("~", "fstab", "/etc/fstab", "regenerate filesystem table",
      function() sync.write_file(path, desired) end),
  }
end

return gen
