local gen = {}
gen.name = "ssh"

function gen.plan(cfg, sync)
  if not cfg.ssh.enable then return {} end

  local path = "/etc/ssh/sshd_config"
  local current = sync.read_file(path) or ""
  local desired = "# generated by haliade-synchronize\n"

  desired = desired .. "Port " .. cfg.ssh.port .. "\n"

  if cfg.ssh.permit_root_login then
    desired = desired .. "PermitRootLogin yes\n"
  else
    desired = desired .. "PermitRootLogin prohibit-password\n"
  end

  desired = desired .. "PasswordAuthentication yes\n"
  desired = desired .. "KbdInteractiveAuthentication no\n"
  desired = desired .. "UsePAM yes\n"
  desired = desired .. "X11Forwarding yes\n"
  desired = desired .. "PermitTTY yes\n"
  desired = desired .. "PrintMotd no\n"
  desired = desired .. "AcceptEnv LANG LC_*\n"
  desired = desired .. "Subsystem sftp /usr/libexec/sftp-server\n"

  desired = desired .. "PubkeyAuthentication yes\n"
  desired = desired .. "AuthorizedKeysFile ssh/authorized_keys\n"

  desired = desired .. "\n"

  local changes = {}

  if current ~= desired then
    table.insert(changes, sync.change("~", "ssh", "/etc/ssh/sshd_config", "update SSH daemon configuration",
      function() sync.write_file(path, desired) end))
  end

  if cfg.ssh.authorized_keys and #cfg.ssh.authorized_keys > 0 then
    local keys_content = ""
    for _, key in ipairs(cfg.ssh.authorized_keys) do
      keys_content = keys_content .. key .. "\n"
    end
    local ak_path = "/root/ssh/authorized_keys"
    local current_keys = sync.read_file(ak_path) or ""
    if current_keys ~= keys_content then
      table.insert(changes, sync.change("~", "ssh", ak_path, "update authorized keys",
        function()
          sync.shell("mkdir -p /root/ssh")
          local ok = sync.write_file(ak_path, keys_content)
          if ok then sync.shell("chmod 600 " .. ak_path) end
          return ok
        end))
    end
  end

  return changes
end

return gen
